### ISSUE TITLE
pls add a readme file

### ISSUE THREAD

**Issue by ajagetia2001** [ajagetia2001/HTTP-basics#1]

**Comment by ShivamMittal1802** [comment]
please assign this task to me

**Comment by ajagetia2001** [comment]
ok I will assign you

**Comment by Cronus1007** [comment]
@ajagetia2001 @ShivamMittal1802 Plzzz maek sure first to correct the name of the file from readmee.md to `README.md`

**Comment by ajagetia2001** [comment]
@Cronus1007  thank you for your guidance.

**Comment by ajagetia2001** [comment]
I will positively change it
